### ISSUE TITLE
Add another CustomEvent polyfill implementation

### ISSUE THREAD

**Issue by matyas-igor** [matteobad/detect-autofill#27]
**Describe the solution you'd like**

Maybe it'll make sense to use some existing lib for polyfilling CustomEvent, since there might be problems with preventing default

E.g. in this lib: https://github.com/kumarharsh/custom-event-polyfill they're doing check whether prevent default is working https://github.com/kumarharsh/custom-event-polyfill/blob/master/polyfill.js#L14

**Comment by matteobad** [comment]
Hi @matyas-igor, thank you for helping out, I've just added the polyfill you linked as a dependency and use it instead. Let me know if this solves your problem
